### ISSUE TITLE
Failure with hash_hmac on PDP when logged in

### ISSUE THREAD

**Issue by henkvalk** [falconmedia/belco-hyva#1]
## Steps to produce
1. Enable the Belco module at the M2 Admin and add credentials
2. Login as a customer on Frontend
3. Enter a Product Detail Page

## Expected Result
Showing the product page without failures

## Actual Result
1. No Product Page shown. 
2.  Error drop in screen

```
<script>
    window.belcoConfig = TypeError: hash_hmac(): Argument #2 ($data) must be of type string, null given in /data/web/deployer_production/releases/82/vendor/falconmedia/magento2-belco-hyva/ViewModel/BelcoConfig.php:70
Stack trace:
#0 /data/web/deployer_production/releases/82/vendor/falconmedia/magento2-belco-hyva/ViewModel/BelcoConfig.php(70): hash_hmac()
#1 /data/web/deployer_production/releases/82/vendor/falconmedia/magento2-belco-hyva/ViewModel/BelcoConfig.php(50): Belco\Hyva\ViewModel\BelcoConfig->getConfig()
#2 /data/web/deployer_production/releases/82/vendor/falconmedia/magento2-belco-hyva/view/frontend/templates/belco.phtml(27): Belco\Hyva\ViewModel\BelcoConfig->getSectionData()
#3 /data/web/deployer_production/releases/82/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
#4 /data/web/deployer_production/releases/82/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#5 /data/web/deployer_production/releases/82/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#6 /data/web/deployer_production/releases/82/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#7 /data/web/deployer_production/releases/82/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#8 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#9 /data/web/deployer_production/releases/82/generated/code/Magento/Framework/View/Element/Template/Interceptor.php(23): Magento\Framework\View\Element\Template->fetchView()
#10 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template\Interceptor->fetchView()
#11 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Element/AbstractBlock.php(1128): Magento\Framework\View\Element\Template->_toHtml()
#12 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Element/AbstractBlock.php(1132): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#13 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Element/AbstractBlock.php(676): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#14 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#15 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#16 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#17 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#18 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#19 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#20 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#21 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#22 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#23 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#24 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#25 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#26 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout->renderElement()
#27 /data/web/deployer_production/releases/82/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#28 /data/web/deployer_production/releases/82/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#29 /data/web/deployer_production/releases/82/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#30 /data/web/deployer_production/releases/82/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#31 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#32 /data/web/deployer_production/releases/82/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#33 /data/web/deployer_production/releases/82/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult()
#34 /data/web/deployer_production/releases/82/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent()
#35 /data/web/deployer_production/releases/82/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}()
#36 /data/web/deployer_production/releases/82/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(32): Magento\Framework\View\Result\Page\Interceptor->___callPlugins()
#37 /data/web/deployer_production/releases/82/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult()
#38 /data/web/deployer_production/releases/82/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#39 /data/web/deployer_production/releases/82/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#40 {main}
```

**Comment by henkvalk** [comment]
#2
